routes/web.php
<?php

/*
|--------------------------------------------------------------------------
| Web Routes
|--------------------------------------------------------------------------
|
| Here is where you can register web routes for your application. These
| routes are loaded by the RouteServiceProvider within a group which
| contains the "web" middleware group. Now create something great!
|
*/

Route::get('/', 'Home@showHomePage')->name('home');

Route::get('/login', 'Auth\LoginController@showLoginForm')->name('login');
Route::post('/login', 'Auth\LoginController@wrappedLogin');

Route::get('/registration', 'Auth\RegisterController@showRegistrationForm')->name('registration');
Route::post('/registration', 'Auth\RegisterController@controlledRegistration');

Route::get('/logout', 'Auth\LoginController@logout')->name('logout');

Route::group(['prefix' => 'test', 'as' => 'test.'], function () {
    Route::get('/', 'Test@showIntroPage')->name('home');
    Route::get('/form', 'Test@showTestPage')->middleware('testauth')->name('test');
    Route::get('/login', 'Test@showLoginPage')->name('login');
    Route::get('/registration', 'Test@showRegistrationPage')->name('registration');

    Route::post('/test-submit', 'Test@passTest')->middleware('auth')->name('submit');
    Route::get('/test-submit', 'Test@showGreatPage')->middleware('auth')->name('submit');
});

Route::group(['middleware' => 'auth', 'prefix' => 'cabinet', 'as' => 'cabinet.'], function () {
    Route::get('/', 'Cabinet@showCabinetHomePage')->name('home');
    Route::get('/test/success', 'Cabinet@showCabinetTestSuccessPage')->name('test-success');
    Route::get('/test', 'Cabinet@showCabinetTestPage')->name('test');
    Route::get('/achieve', 'Cabinet@showCabinetAchievePage')->name('achieve');
    Route::get('/tools/success', 'Cabinet@showCabinetToolsSuccessPage')->name('tools-success');
    Route::get('/tools', 'Cabinet@showCabinetToolsPage')->name('tools');
});

resources/views/home.blade.php
<!doctype html>
<html lang="{{ str_replace('_', '-', app()->getLocale()) }}">
<head>
  <meta charset="UTF-8">
  <meta name="viewport"
        content="width=device-width, user-scalable=no, initial-scale=1.0, maximum-scale=1.0, minimum-scale=1.0">
  <meta http-equiv="X-UA-Compatible" content="ie=edge">
  <title>Nomad Home</title>
  <link rel="stylesheet" href="{{ mix('/css/app.css') }}">
</head>
<body>
  <div class="p-home">
    <div class="l-header">
      @include('components.header')
    </div>
    <div class="l-navigation">
      @include('components.navigation', ['options' =>
        [
          [
            'anchor' => '/#hero',
            'text' => ''
          ],
          [
            'anchor' => '/#best-tools',
            'text' => '30 BEST TOOLS'
          ],
          [
            'anchor' => '/#flag-theory',
            'text' => 'FLAG THEORY'
          ],
          [
            'anchor' => '/#how-it-work',
            'text' => 'HOW IT WORKS'
          ],
          [
            'anchor' => '/#events',
            'text' => 'EVENTS'
          ],
          [
            'anchor' => '/#tests',
            'text' => 'TEST'
          ]
        ]
      ])
    </div>
    @include('components.hero', [
      'title' => 'Limitless. Secure. Wealthy.',
      'video' => '/storage/common/hero-video.mp4',
      'text' => 'Nomad Family is a worldwide network that helps thousands of people to transform their lives and achieve goals by traveling, living in any country they want, and building businesses as easy as ABC.'
    ])
    @include('components.about-short')
    <div class="uk-margin-xlarge-top">
      @include('components.citation')
    </div>
    <div class="uk-margin-large-top">
      @include('components.world-wide')
    </div>
    <div class="uk-margin-xlarge-top">
      @include('components.possibilities')
    </div>
    @include('components.fillup')
    <div class="uk-margin-xlarge-top" id="best-tools">
      @include('components.best-tools')
    </div>
    <div class="uk-margin-xlarge-top" id="flag-theory">
      @include('components.theory')
    </div>
    <div class="l-flags">
      <div class="u-container">
        @include('components.flags')
      </div>
    </div>
    <div class="l-how-works" id="how-it-work">
      <div class="u-container">
        @include('components.how-works')
      </div>
    </div>
    @include('components.profit')
    <div class="l-meeting" id="events">
      @include('components.meeting')
    </div>
    <div class="l-who">
      @include('components.who')
    </div>
    <div class="l-around">
      <div class="u-container">
        @include('components.around')
      </div>
    </div>
    <div class="l-upwork-stats">
      @include('components.upwork-stats')
    </div>
    <div class="l-club">
      @include('components.club')
    </div>
    <div class="l-criteria" id="tests">
      @include('components.criteria')
    </div>
    <div class="l-journey-box">
      @include('components.journey-box')
    </div>
    <div class="l-travel">
      @include('components.travel')
    </div>
    <div class="l-footer">
      <div class="u-container">
        @include('components.footer')
      </div>
    </div>
  </div>

  @include('components.mobile-menu')

<script src="{{ mix('/js/app.js') }}"></script>
</body>
</html>

resources/views/login.blade.php
<?php if (!isset($redirect)) $redirect = route('cabinet.home') ?>

@extends('layouts.full-size')

@section('title', 'Login')
@section('page', 'login')
@section('content')
  @include('components.form-login', ['redirect' => $redirect])
@endsection

resources/views/registration.blade.php
<?php if (!isset($redirect)) $redirect = route('cabinet.home') ?>

@extends('layouts.full-size')

@section('title', 'Registration')
@section('page', 'registration')
@section('content')
  @include('components.form-register', ['redirect' => $redirect])
@endsection

resources/views/ui.blade.php
<!doctype html>
<html lang="{{ str_replace('_', '-', app()->getLocale()) }}">
<head>
  <meta charset="UTF-8">
  <meta name="viewport"
        content="width=device-width, user-scalable=no, initial-scale=1.0, maximum-scale=1.0, minimum-scale=1.0">
  <meta http-equiv="X-UA-Compatible" content="ie=edge">
  <title>Document</title>
  <link rel="stylesheet" href="{{ mix('/css/ui.css') }}">
  <link rel="stylesheet" href="{{ mix('/css/app.css') }}">
</head>
<body>
  <div class="p-ui uk-margin-top uk-margin-left uk-margin-right">

    <div class="uk-grid-column-small" uk-grid>
      <div class="uk-width-2-5">
        @include('examples.title-card')
      </div>
      <div class="uk-width-3-5">
        @include('examples.input-card')
        <div class="uk-margin-top">
          @include('examples.spinner-card')
        </div>
      </div>
      <div class="uk-width-2-5">
        @include('examples.text-card')
      </div>
      <div class="uk-width-3-5">
        @include('examples.error-card')
        <div class="uk-margin-top">
          @include('examples.link-card')
        </div>
      </div>
      <div class="uk-width-2-5">
        @include('examples.logo-card')
      </div>
      <div class="uk-width-3-5">
        @include('examples.checkbox')
      </div>
      <div class="uk-width-2-5">
        @include('examples.social-card')
        <div class="uk-margin-top">
          @include('examples.line-card')
        </div>
      </div>
      <div class="uk-width-3-5">
        @include('examples.button-card')
      </div>
      <div class="uk-width-2-5">
        @include('examples.quote')
      </div>
      <div class="uk-width-3-5">
        @include('examples.range-card')
      </div>
      <div class="uk-width-2-5">
        @include('examples.card')
      </div>
      <div class="uk-width-3-5">
        @include('examples.flag')
      </div>
      <div class="uk-width-2-5">
        @include('examples.navigation')
      </div>
      <div class="uk-width-3-5">
        @include('examples.spiral-gold')
      </div>
      <div class="uk-width-2-5">
        @include('examples.flag-progress')
      </div>
      <div class="uk-width-3-5">
        @include('examples.dropdown')
      </div>
      <div class="uk-width-2-5">
        @include('examples.ballons')
      </div>
      <div class="uk-width-3-5">
        @include('examples.form-criteria')
      </div>
      <div class="uk-width-2-5">
        @include('examples.members-counter')
      </div>
      <div class="uk-width-3-5">
        @include('examples.stopline-card')
      </div>
      <div class="uk-width-1-1">
        @include('examples.video')
      </div>
      <div class="uk-width-1-1">
        @include('examples.hs-slider')
      </div>
    </div>

    <div class="uk-grid-column-small" uk-grid>
      <div class="uk-width-1-1">
        @include('examples.header')
      </div>
      <div class="uk-width-1-1">
        @include('examples.hero')
      </div>
      <div class="uk-width-1-1">
        @include('examples.about-short')
      </div>
      <div class="uk-width-1-1">
        @include('examples.citation')
      </div>
      <div class="uk-width-1-1">
        @include('examples.map')
      </div>
      <div class="uk-width-1-1">
        @include('examples.possibilities')
      </div>
      <div class="uk-width-1-1">
        @include('examples.fillup')
      </div>
      <div class="uk-width-1-1">
        @include('examples.best-tools')
      </div>
      <div class="uk-width-1-1">
        @include('examples.theory')
      </div>
      <div class="uk-width-1-1">
        @include('examples.flags')
      </div>
      <div class="uk-width-1-1">
        @include('examples.how-works')
      </div>
      <div class="uk-width-1-1">
        @include('examples.profit')
      </div>
      <div class="uk-width-1-1">
        @include('examples.meeting')
      </div>
      <div class="uk-width-1-1">
        @include('examples.who')
      </div>
      <div class="uk-width-1-1">
        @include('examples.around')
      </div>
      <div class="uk-width-1-1">
        @include('examples.upwork-stats')
      </div>
      <div class="uk-width-1-1">
        @include('examples.club')
      </div>
      <div class="uk-width-1-1">
        @include('examples.criteria')
      </div>
      <div class="uk-width-1-1">
        @include('examples.journey-box')
      </div>
      <div class="uk-width-1-1">
        @include('examples.travel')
      </div>
      <div class="uk-width-1-1">
        @include('examples.footer')
      </div>
    </div>

    <div class="uk-grid-column-small" uk-grid>
      <div class="uk-width-1-1">
        @include('examples.test-intro')
      </div>
      <div class="uk-width-1-1">
        @include('examples.form')
      </div>
      <div class="uk-width-1-1">
        @include('examples.user')
      </div>
      <div class="uk-width-2-5">
        @include('examples.personal-card')
      </div>
      <div class="uk-width-3-5">
        @include('examples.card-advanced')
      </div>
      <div class="uk-width-1-1">
        @include('examples.features-centered')
      </div>
    </div>

  </div>

  <script src="{{ mix('/js/ui.js') }}"></script>
  <script src="{{ mix('/js/app.js') }}"></script>
</body>
</html>